before_script:
  - bash ci/docker_install.sh > /dev/null

stages:
  - build
  - test

job_build_php5.6_centos7:
  image: centos7
  stage: build
  script:
    - composer self-update
    - composer install
    
job_build_php5.6_centos6:
  image: centos6
  stage: build
  script:
    - composer self-update
    - composer install

job_test:
  stage: test
  script:
    - phpunit

variables:
  GIT_SSL_NO_VERIFY: "true"