stages:
  - build
  - test

job_build_php5.6_centos7:
  image: centos:7
  stage: build
  script:
    - yum update -y
    - yum install -y php
    - php --version

job_test:
  stage: test
  script:
    - phpunit

variables:
  GIT_SSL_NO_VERIFY: "true"