stages:
  - build
  - test

job_build_php5.6_centos7:
  image: centos:7
  services:
    - php:5.6
  stage: build
  script:
    - php --version
    
job_build_php5.6_centos6:
  image: centos:6
  services:
    - php:5.6
  stage: build
  script:
    - php --version

job_build_php7_centos7:
  image: centos:7
  stage: build
  services:
    - php:7
  script:
    - php --version
    
job_build_php7_centos6:
  image: centos:6
  services:
    - php:7
  stage: build
  script:
    - php --version

job_test:
  stage: test
  script:
    - phpunit

variables:
  GIT_SSL_NO_VERIFY: "true"