image: php:5.6

before_script:
- bash ci/docker_install.sh > /dev/null

stages:
  - build
  - test

job1:
  image: php:5.6
  stage: build
  script:
    - composer self-update
    - composer install
    - phpunit --configuration phpunit.xml

variables:
  GIT_SSL_NO_VERIFY: "true"